import type { Song, Concert, User } from './types';

export const users: User[] = [
  {
    id: '1',
    name: 'Sheryl Schnare',
    role: 'Music Director',
    email: 'sheryl.schnare@example.com',
  },
  {
    id: '2',
    name: 'David Reed',
    role: 'Librarian',
    email: 'david.reed@example.com',
  },
  {
    id: '3',
    name: 'Maria Rossi',
    role: 'Musician',
    email: 'maria.rossi@example.com',
  },
];

export const songs: Song[] = [
  {
    id: '1',
    title: 'Symphony No. 5',
    composer: 'Ludwig van Beethoven',
    lyricist: 'N/A',
    arranger: 'N/A',
    copyright: 'Public Domain',
    publisher: 'Breitkopf & Härtel',
    catalogNumber: 'Op. 67',
    quantity: 1,
    type: 'Orchestral',
    lastPerformed: '2023-10-28',
    performanceHistory: [{ date: '2023-10-28', concertName: 'Fall Gala' }],
  },
  {
    id: '2',
    title: 'The Planets',
    composer: 'Gustav Holst',
    lyricist: 'N/A',
    arranger: 'N/A',
    copyright: 'Public Domain',
    publisher: 'Goodwin & Tabb',
    catalogNumber: 'Op. 32',
    quantity: 1,
    type: 'Orchestral',
    lastPerformed: '2023-05-15',
    performanceHistory: [{ date: '2023-05-15', concertName: 'Spring Festival' }],
  },
  {
    id: '3',
    title: 'Hallelujah Chorus',
    composer: 'George Frideric Handel',
    lyricist: 'Charles Jennens',
    arranger: 'N/A',
    copyright: 'Public Domain',
    publisher: 'Broude Brothers',
    catalogNumber: 'HWV 56',
    quantity: 50,
    type: 'Choral',
    lastPerformed: '2022-12-20',
    performanceHistory: [{ date: '2022-12-20', concertName: 'Holiday Pops' }],
  },
  {
    id: '4',
    title: 'Adagio for Strings',
    composer: 'Samuel Barber',
    lyricist: 'N/A',
    arranger: 'N/A',
    copyright: '© 1938 G. Schirmer Inc.',
    publisher: 'G. Schirmer',
    catalogNumber: 'Op. 11',
    quantity: 1,
    type: 'Orchestral',
    performanceHistory: [],
  },
  {
    id: '5',
    title: 'Bohemian Rhapsody',
    composer: 'Freddie Mercury',
    lyricist: 'Freddie Mercury',
    arranger: 'John Doe',
    copyright: '© 1975 Queen Music Ltd.',
    publisher: 'Hal Leonard',
    catalogNumber: 'HL00123456',
    quantity: 60,
    type: 'Choral',
    lastPerformed: '2023-05-15',
    performanceHistory: [{ date: '2023-05-15', concertName: 'Spring Festival' }],
  },
    {
    id: '6',
    title: 'The Four Seasons',
    composer: 'Antonio Vivaldi',
    lyricist: 'N/A',
    arranger: 'N/A',
    copyright: 'Public Domain',
    publisher: 'Ricordi',
    catalogNumber: 'Op. 8',
    quantity: 1,
    type: 'Orchestral',
    performanceHistory: [],
  },
  {
    id: '7',
    title: 'Eine kleine Nachtmusik',
    composer: 'Wolfgang Amadeus Mozart',
    lyricist: 'N/A',
    arranger: 'N/A',
    copyright: 'Public Domain',
    publisher: 'Bärenreiter',
    catalogNumber: 'K. 525',
    quantity: 1,
    type: 'Chamber',
    lastPerformed: '2021-08-01',
    performanceHistory: [{ date: '2021-08-01', concertName: 'Summer Serenade' }],
  },
];

export const concerts: Concert[] = [
  {
    id: '1',
    name: 'Fall Gala',
    date: '2023-10-28',
    pieces: [songs[0]],
  },
  {
    id: '2',
    name: 'Spring Festival',
    date: '2023-05-15',
    pieces: [songs[1], songs[4]],
  },
  {
    id: '3',
    name: 'Holiday Pops',
    date: '2022-12-20',
    pieces: [songs[2]],
  },
];
